version: 2.1

orbs:
  # Official CircleCI Maven orb – latest release is v2.0.0
  maven: circleci/maven@2.0.0  # :contentReference[oaicite:0]{index=0}
  # Official CircleCI Docker orb – latest release is v2.8.2
  docker: circleci/docker@2.8.2  # :contentReference[oaicite:1]{index=1}

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      # Restore your Maven dependency cache
      - maven/cache
      - run:
          name: Build & Run Tests
          command: mvn clean verify -DskipTests=false
      # Save the updated Maven dependency cache
      - maven/save

  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t your_dockerhub_user/transaction-service:${CIRCLE_SHA1} .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Push to DockerHub
          command: |
            docker push your_dockerhub_user/transaction-service:${CIRCLE_SHA1}
            docker tag your_dockerhub_user/transaction-service:${CIRCLE_SHA1} your_dockerhub_user/transaction-service:latest
            docker push your_dockerhub_user/transaction-service:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - build-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
