version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  docker: circleci/docker@2.8.2  # 可保留原本 2.3.0

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: mvn clean verify
  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Debug env
          command: |
            echo "DOCKERHUB_USER is '$DOCKERHUB_USER'"
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" \
            | docker login --username "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USER/transaction-service:${CIRCLE_SHA1} .
      - run:
          name: Push to DockerHub
          command: |
            docker push $DOCKERHUB_USER/transaction-service:${CIRCLE_SHA1}
            docker tag $DOCKERHUB_USER/transaction-service:${CIRCLE_SHA1} \
                       $DOCKERHUB_USER/transaction-service:latest
            docker push $DOCKERHUB_USER/transaction-service:latest

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build-docker-image:
          requires:
            - test
          filters:
            branches:
              only: main
