apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service-container
          image: your_docker_registry/transaction-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              value: transaction-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: jwt-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: transaction-service-config
            items:
              - key: application.yml
                path: application.yml
