apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service-container
          image: k3d-myregistry:5000/transaction-service:latest
          #image: transaction-service:latest
          # 不要從 registry 拉
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yml"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              value: host.docker.internal
            - name: POSTGRES_PORT
              value: "5432"
            # RSA 公私鑰
            - name: SPRING_SECURITY_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: jwt-public-key

            - name: SPRING_SECURITY_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: jwt-private-key

            # 失效時間
            - name: SPRING_SECURITY_JWT_EXPIRATION_IN_MS
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secret
                  key: jwt-expiration-in-ms               
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: transaction-service-config
            items:
              - key: application.yml
                path: application.yml
